### PR TITLE
Fixes for streaming from live555 RTSP servers

### PR DESCRIPTION
**Pull request by tartanpaint**
Fixes for streaming from live555 RTSP server - this requires the use of the base URI from the DESCRIBE response to be used in the PLAY request.
Construct track URLs correctly in Client::onDescribeResponse when accessing streams on private network.

This allows successful streaming from live555 RTSP servers with URLs of the form:
rtsp://user:password@192.168.0.10/video?input=0&profile=primary&transport=unicast

### CODE REVIEW

**Review by portizb — CHANGES_REQUESTED** [review]
I think it would be better to have the getPlayUrl method on the Client class in order to abstract the implementation in the base class.

**Comment by tartanpaint** [comment]
No problem, I've moved the getPlayUrl method to Client class now

**Comment by portizb** [comment]
> No problem, I've moved the getPlayUrl method to Client class now

@tartanpaint thanks!! ;)

**Review by portizb — APPROVED** [review]

**Review by portizb — APPROVED** [review]

**Review by portizb — APPROVED** [review]

**Review by portizb — APPROVED** [review]

**Review by portizb — APPROVED** [review]

**Comment by portizb** [comment]
@tartanpaint  I will apply your changes manually because if I do it from here this branch would break because the merge pull request #6 from google/dev-v2 cannot do it automatically.

**Pull request closed without merging**
